apiVersion: apps/v1
kind: Deployment
metadata:
  name: divyank-deployment
  labels:
    app: first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
        - name: first
          image: divyank666/test_server:sha-a9a8c9c
          ports:
            - containerPort: 8081